Develop 29 geluids effecten Compleet
Brack-Engine/Brack-Engine pull request #137
Opened 2023-11-10 03:19 UTC by JamesAndrewKong

Use the Branch "TEST29Geluiden" in Brackocalypse to test the branch.

Notable Additions:
AudioSystem. (Using available components, it runs AudioWrapper functions depending on component variables, also is responsible for changing audiocomponent variables if needed.

AudioComponent:
    bool isLooping
    bool isPlaying (AudioSystem updates this state depending on the whether the audiofile is currently playing, right now 0 uses)
    bool shouldBePlaying (If turned on, will play the audiofile)
    int duration (AudioWrapper adds the duration in milliseconds for how long the uploaded audio takes upon upload)

AudioWrapper:
Communicates with FMOD and handles all AudioSystem requests related to the FMOD library.

Notable changes:
-Added  std::vector<T*> GetComponents(uint32_t entity) to componentstore

2023-11-17 23:47 UTC, JamesAndrewKong commented on lib/FMod/libfmod.so.13
Symbolic Link gemaakt via Powershell, enige manier hoe het lukte, en wat git settings aangepast om het te kunnen committen zonder dat github het convert naar een ander bestand.

2023-11-20 10:47 UTC, Quintemp99 requested changes
Het ziet er beter uit maar we hadden wel gezegd dat je ook rekening moest houden met het feit dat de audiocomponents ook op pauze gezet moeten kunnen worden uiteindelijk. Maar daar zie ik niks van terug.

Wat is er gebeurd dat je een symbolic link nodig hebt. Naar welke plek wijst de symbolic link?

2023-11-20 10:47 UTC, Quintemp99 commented on outfacingInterfaces/Components/Archetypes/AudioArchetype.hpp
Dit hoeft geen class the zijn maar een struct.

2023-11-20 14:37 UTC, JamesAndrewKong commented on outfacingInterfaces/Components/Archetypes/AudioArchetype.hpp
De symbolic link wijst naar de nieuwe versie van libfmod.so

Op Unix systemen heeft FMod een nieuwe versie, en een generieke FMod .so die er naar toe wijst. In tegenstelling tot 1 DLL op windows.

2023-11-20 15:37 UTC, Quintemp99 commented on outfacingInterfaces/Components/Archetypes/AudioArchetype.hpp
Kan je niet gewoon de symbolic link naar de nieuwe versie van libfmod.so weg halen en de daadwerkelijke nieuwe libfmod.so daar plaatsen?

2023-11-20 17:36 UTC, JamesAndrewKong commented on outfacingInterfaces/Components/Archetypes/AudioArchetype.hpp
Je kan het zelf ook proberen, ik heb dat 10x gedaan als je 1 weghaalt vraagt hij om de ander, als je de ander weghaalt vraagt hij om de ene.

2023-11-20 17:38 UTC, JamesAndrewKong commented on outfacingInterfaces/Components/Archetypes/AudioArchetype.hpp
Ik heb Pause geimplementeerd, en de bijbehorende resume die werkt bij de huidige werkwijze van audiosystem.

2023-11-20 17:39 UTC, JamesAndrewKong commented on outfacingInterfaces/Components/Archetypes/AudioArchetype.hpp
en class naar struct gewijzigd

2023-11-21 09:10 UTC, Quintemp99 commented on outfacingInterfaces/Components/Archetypes/AudioArchetype.hpp
Ik heb het zelf gedaan, sorry maar heb de library binnen 10 minuten werkend gekregen met 1 libfmod.so.13 file.

2023-11-21 09:13 UTC, Quintemp99 reviewed
Regel even de merge conflicts en zorg dat de functies en variablen camelcase zijn want dat is gisteren besproken tijdens de standup. Dan is het goed.

2023-11-28 10:49 UTC, Quintemp99 approved these changes

2023-11-28 18:40 UTC, jMampaey requested changes
Werkt niet op mingw

2023-11-30 14:28 UTC, merged