Feature/Collision
Brack-Engine/Brack-Engine pull request #180
Opened 2023-11-22 13:13 UTC by UndertokerI

# Checklist

## Code kwaliteit
- [x] Functies, variablen en classes gebruiken de juiste casing
- [x] Code is duidelijk en begrijplijk (eventueel comentaar voor meer duidelijkheid)
- [x] Functies zijn compact en doen alleen wat de functie naam impliceert

## Testen
-	[x] De applicatie runned via MinGW
-	[x] De applicatie runned een POSIX-systeem
-	[x] De applicatie geeft geen waarschuwingen
-	[x] De functionaliteit voldoet aan de user story van de klant
-	[x] Er is een good flow getest
-	[x] Er is een bad flow getest

Werking: collision slaat op welk component er in contact is. Behaviourscripts zal moeten afhandelen wat hiermee gebeurd. 
Eventuele problemen: Box2d wordt nu als los project meegecompiled ik heb hier onderzoek naar gedaan en geen mogelijkheid gevonden om dit niet te doen.
addCircle en addBoxes hebben veel duplicate code. Dit kan nog gerefactored worden. 

Close: #126 #83 #82 #83 #25 #24 #23

2023-11-23 10:22 UTC, Stef-van-Stipdonk requested changes
Zorg er ook even voor dat je het pr template invult.
Voor de rest werkt het nu ook op mac.

2023-11-23 10:22 UTC, Stef-van-Stipdonk commented on src/Wrappers/PhysicsWrapper.cpp
> +void ContactListener::BeginContact(b2Contact *contact) {
Camel casing please

2023-11-23 10:22 UTC, Stef-van-Stipdonk commented on src/Wrappers/PhysicsWrapper.cpp
> +void ContactListener::EndContact(b2Contact *contact) {
Camel casing please

2023-11-23 10:22 UTC, Stef-van-Stipdonk commented on src/Wrappers/PhysicsWrapper.hpp
> +    void Initialize();
Camel casing please

2023-11-23 10:22 UTC, Stef-van-Stipdonk commented on src/Wrappers/PhysicsWrapper.hpp
>      void Cleanup();
Camel casing please

2023-11-23 10:22 UTC, Stef-van-Stipdonk commented on src/Wrappers/PhysicsWrapper.hpp
> +    void BeginContact(b2Contact *contact) override;
Camel casing please

2023-11-23 10:22 UTC, Stef-van-Stipdonk commented on src/Wrappers/PhysicsWrapper.hpp
> +    void EndContact(b2Contact *contact) override;
Camel casing please

2023-11-24 13:19 UTC, jMampaey approved these changes

2023-11-24 13:20 UTC, Stef-van-Stipdonk approved these changes
lgtm

2023-11-24 13:20 UTC, merged