Bug/switch scene
Brack-Engine/Brack-Engine pull request #197
Opened 2023-12-04 20:00 UTC by StijnLingmont

Bij het switchen van scenes worden nu alle (al bestaande) cached variables in systems gereleased en componenten correct eruit gehaald.

# Checklist

## Code kwaliteit
- [ ] Functies, variablen en classes gebruiken de juiste casing
- [ ] Code is duidelijk en begrijplijk (eventueel comentaar voor meer duidelijkheid)
- [ ] Functies zijn compact en doen alleen wat de functie naam impliceert

## Testen
-	[ ] De applicatie runned via MinGW
-	[ ] De applicatie runned een POSIX-systeem
-	[ ] De applicatie geeft geen waarschuwingen
-	[ ] De functionaliteit voldoet aan de user story van de klant
-	[ ] Er is een good flow getest
-	[ ] Er is een bad flow getest

2023-12-05 08:24 UTC, Stef-van-Stipdonk commented
Ik review je pr niet, maar doe ff het template invullen

2023-12-05 19:13 UTC, UndertokerI requested changes
willen we de box2d wereld niet ook clearen

2023-12-05 19:13 UTC, UndertokerI commented on src/Objects/Scene.cpp
> +//    AddCamera(Camera());
wrm is dit uitgecommend?

2023-12-07 13:14 UTC, UndertokerI approved these changes
lgtm

2023-12-07 13:20 UTC, merged